name: which-branch
description:
  "Discover and report which repository branch corresponds to `github.repository`'s `github.sha`."

inputs:
  token:
    description: "GitHub Personal Access Token with which to query the REST API"
    required: true

outputs:
  branch:
    description: "Branch whose tip is used for this build"
    value: ${{ steps.which-branch.outputs.branch }}

runs:
  using: composite
  steps:
    - name: Determine which branch
      id: which-branch
      shell: bash
      run: |
        set -x
        if [[ "$GITHUB_REF_TYPE" != "tag" ]]
        then
            # For a pull request, GITHUB_HEAD_REF is the branch name.
            # For a branch build, GITHUB_REF_NAME is the branch name.
            branch="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
        else
            # For a tag build, have to discover which branch corresponds.
            pip3 install PyGithub
            branch="$(python '${{ github.action_path }}/which_branch.py' \
                      -t "${{ inputs.token }}" -r "${{github.repository }}" "${{ github.sha }}")"
        fi
        echo "branch=$branch" >> "$GITHUB_OUTPUT"
