name: sign-pkg-mac
description:
  Sign and package the macOS Linden viewer.

##inputs:
##  channel:
##    description: "Viewer channel"
##    type: string
##    required: true
##  version:
##    description: "Viewer version"
##    type: string
##    required: true

runs:
  using: composite
  steps:
    - name: Fetch Mac app
      uses: actions/download-artifact@v3
      with:
        name: macOS-app
        path: .app
