name: sign-pkg-windows
description:
  Sign and package the Windows Linden viewer.

##inputs:
##  channel:
##    description: "Viewer channel"
##    type: string
##    required: true
##  version:
##    description: "Viewer version"
##    type: string
##    required: true

runs:
  using: composite
  steps:
    - name: Fetch Windows app
      uses: actions/download-artifact@v3
      with:
        name: Windows-app
        path: .app
